### ISSUE TITLE
--disable-zoned no longer works in 5.16.1: build failure

### ISSUE THREAD

**Issue by kanavin** [kdave/btrfs-progs#449]
The following failure occurs:
```
| /home/alex/development/poky/build-64-alt/tmp/work/core2-64-poky-linux/btrfs-tools/5.16.1-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/../../libexec/x86_64-poky-linux/gcc/x86_64-poky-linux/11.2.0/ld: mkfs/main.o: in function `main':
| /usr/src/debug/btrfs-tools/5.16.1-r0/git/mkfs/main.c:1352: undefined reference to `zoned_profile_supported'
| /home/alex/development/poky/build-64-alt/tmp/work/core2-64-poky-linux/btrfs-tools/5.16.1-r0/recipe-sysroot-native/usr/bin/x86_64-poky-linux/../../libexec/x86_64-poky-linux/gcc/x86_64-poky-linux/11.2.0/ld: /usr/src/debug/btrfs-tools/5.16.1-r0/git/mkfs/main.c:1353: undefined reference to `zoned_profile_supported'
| collect2: error: ld returned 1 exit status
| make: *** [Makefile:630: mkfs.btrfs] Error 1
```

**Comment by kdave** [comment]
Thanks for the report. This has been fixed in devel branch and will be released in 5.16.2 soon.
