### ISSUE TITLE
Can't compile from latest release (5.15.1) - error: linux/blkzoned.h does not provide blk_zone.capacity

### ISSUE THREAD

**Issue by MechDR** [kdave/btrfs-progs#425]
Error.

```
checking for linux/blkzoned.h... yes
checking for struct blk_zone.capacity... no
checking for BLKGETZONESZ defined in linux/blkzoned.h... yes
configure: error: linux/blkzoned.h does not provide blk_zone.capacity
```

Yes, it's not defined in `/usr/include/linux/blkzoned.h`.

```
struct blk_zone {
	__u64	start;		/* Zone start sector */
	__u64	len;		/* Zone length in number of sectors */
	__u64	wp;		/* Zone write pointer position */
	__u8	type;		/* Zone type */
	__u8	cond;		/* Zone condition */
	__u8	non_seq;	/* Non-sequential write resources active */
	__u8	reset;		/* Reset write pointer recommended */
	__u8	reserved[36];
};
```

But, it's defined in `/usr/src/linux-hwe-5.11-headers-5.11.0-40/include/uapi/linux/blkzoned.h`.

```
struct blk_zone {
	__u64	start;		/* Zone start sector */
	__u64	len;		/* Zone length in number of sectors */
	__u64	wp;		/* Zone write pointer position */
	__u8	type;		/* Zone type */
	__u8	cond;		/* Zone condition */
	__u8	non_seq;	/* Non-sequential write resources active */
	__u8	reset;		/* Reset write pointer recommended */
	__u8	resv[4];
	__u64	capacity;	/* Zone capacity in number of sectors */
	__u8	reserved[24];
```

So, I just backed up the original `blkzoned.h` and made a symlink to the `blkzoned.h` in `/usr/src/linux-hwe-5.11-headers-5.11.0-40/include/uapi/linux/blkzoned.h`... nope, still doesn't compile and throws the same error. All dependencies installed from Ubuntu repo (OS: xUbuntu 20.04 LTS AMD64).

**Comment by kdave** [comment]
I think the directory /usr/include/linux is a symlink to the latest kernel headers, but it's not the same thing as kernel source package. Eg. on openSUSE there's linux-glibc-devel that contains the files for `/usr/include/linux`, while kernel-source populates `/usr/src/linux-...`.

So you need to update the first package, the minimum version providing the `blk_zone.capacity` is 5.10.

**Comment by kdave** [comment]
https://github.com/kdave/btrfs-progs/issues/370

**Comment by MechDR** [comment]
I meant "I made a symlink from `blkzoned.h` **located** in `/usr/src/linux-hwe-5.11-headers-5.11.0-40/include/uapi/linux/blkzoned.h` to the one located in `/usr/include/linux/blkzoned.h`"... meaning, I symlinked the file correct file to the location the compiler was asking for.

Nevertheless, just in case, I backed up `/usr/include/linux` to `/usr/include/linux.bak`, deleted `/usr/include/linux` and than copied (not symlinked) everything from `/usr/src/linux-hwe-5.11-headers-5.11.0-40/include/uapi/linux/` and the compiler still exits with the same error.

```
checking for linux/blkzoned.h... yes
checking for struct blk_zone.capacity... no
checking for BLKGETZONESZ defined in linux/blkzoned.h... yes
configure: error: linux/blkzoned.h does not provide blk_zone.capacity
```
I manually checked if `blk_zone.capacity` is defined in `/usr/include/linux/blkzoned.h` now, it is.

```
struct blk_zone {
	__u64	start;		/* Zone start sector */
	__u64	len;		/* Zone length in number of sectors */
	__u64	wp;		/* Zone write pointer position */
	__u8	type;		/* Zone type */
	__u8	cond;		/* Zone condition */
	__u8	non_seq;	/* Non-sequential write resources active */
	__u8	reset;		/* Reset write pointer recommended */
	__u8	resv[4];
	__u64	capacity;	/* Zone capacity in number of sectors */
	__u8	reserved[24];
```

**Comment by kdave** [comment]
You can check what exacly happened in the file config.log, it may be a different error.

**Comment by MechDR** [comment]
Well, here's the whole log... and the part that matters.

```
configure:6583: checking for struct blk_zone.capacity
configure:6583: gcc -c -g -O1 -Wall -D_FORTIFY_SOURCE=2  conftest.c >&5
conftest.c: In function 'main':
conftest.c:41:12: error: 'struct blk_zone' has no member named 'capacity'
   41 | if (ac_aggr.capacity)
      |            ^
conftest.c:40:24: warning: variable 'ac_aggr' set but not used [-Wunused-but-set-variable]
   40 | static struct blk_zone ac_aggr;
      |                        ^~~~~~~
```
[config.log.zip](https://github.com/kdave/btrfs-progs/files/7603724/config.log.zip)

**Comment by kdave** [comment]
That's indeed the error, missing capacity member. I don't know what could go wrong here, the file has the definition but config test does not see, that's weird.

**Comment by MechDR** [comment]
Could it possibly be caching? I restarted a few times just to be sure the kernel is not holding anything in cache...

**Comment by MechDR** [comment]
And somehow (magically :D), it works on my laptop with xUbuntu 20.04... have no idea how.

```
configure:6575: checking linux/blkzoned.h presence
configure:6575: gcc -E  conftest.c
In file included from /usr/include/linux/blkzoned.h:19,
                 from conftest.c:33:
`
[config.log.zip](https://github.com/kdave/btrfs-progs/files/7605357/config.log.zip)
``

**Comment by kdave** [comment]
From the config log:

```
configure:6575: checking linux/blkzoned.h usability
configure:6575: gcc -c -g -O1 -Wall -D_FORTIFY_SOURCE=2  conftest.c >&5
In file included from /usr/include/linux/stat.h:5,
                 from /usr/include/x86_64-linux-gnu/bits/statx.h:31,
                 from /usr/include/x86_64-linux-gnu/sys/stat.h:446,
                 from conftest.c:38:
/usr/include/linux/types.h:10:2: warning: #warning "Attempt to use kernel headers from user space, see https://kernelnewbies.org/KernelHeaders" [-Wcpp]
   10 | #warning "Attempt to use kernel headers from user space, see https://kernelnewbies.org/KernelHeaders"
      |  ^~~~~~~
In file included from /usr/include/linux/posix_types.h:5,
                 from /usr/include/linux/types.h:14,
                 from /usr/include/linux/stat.h:5,
                 from /usr/include/x86_64-linux-gnu/bits/statx.h:31,
                 from /usr/include/x86_64-linux-gnu/sys/stat.h:446,
                 from conftest.c:38:
/usr/include/linux/stddef.h:2:10: fatal error: linux/compiler_types.h: No such file or directory
    2 | #include <linux/compiler_types.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

IOW, you're not supposed to link the files directly. There are no other similar reports so it's specific to your setup, I don't know how to help.

**Comment by joelcarlton** [comment]
I believe I am having the same issue.

`configure:6544: checking for linux/blkzoned.h
configure:6544: result: yes
configure:6552: checking for struct blk_zone.capacity
configure:6552: gcc -c -g -O1 -Wall -D_FORTIFY_SOURCE=2  conftest.c >&5
conftest.c: In function 'main':
conftest.c:41:12: error: 'struct blk_zone' has no member named 'capacity'
   41 | if (ac_aggr.capacity)
      |            ^
conftest.c:40:24: warning: variable 'ac_aggr' set but not used [-Wunused-but-set-variable]
   40 | static struct blk_zone ac_aggr;
      |`

**Comment by kdave** [comment]
You can do `configure --disable-zoned` to completely skip the detection. I'll try to figure out how to make it fall back to no-zoned in case the member is not found, or at least give a hint in the error message about the option.

**Comment by kdave** [comment]
The autodetection has been fixed and it should work now in your setup, not enabling the zoned mode in case the capacity struct member is missing. I've simulated and tested all three cases here but please also test it in your setup.
